openapi: 3.1.0
info:
  title: Express Starter API
  version: 24-05
paths:
  /v1/auth/login:
    post:
      operationId: PostV1AuthLogin
      summary: Login
      description: Login with email and password, you will get the token.
      requestBody:
        description: POST /v1/auth/login Request body
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
                - email
                - password
      responses:
        "200":
          description: POST /v1/auth/login Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token
                required:
                  - status
                  - data
        "400":
          description: POST /v1/auth/login Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /v1/auth/hello:
    get:
      operationId: GetV1AuthHello
      summary: Protected route - example
      description: You can't access this endpoint without valid Bearer token in Header
        - authorization.
      security:
        - APIKEY_1: []
      responses:
        "200":
          description: GET /v1/auth/hello Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      greetings:
                        type: string
                    required:
                      - greetings
                required:
                  - status
                  - data
        "400":
          description: GET /v1/auth/hello Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /v1/auth/refresh-token:
    post:
      operationId: PostV1AuthRefreshToken
      summary: Refresh the access token
      description: If already authenticated, this endpoint will send a new access token.
      requestBody:
        description: POST /v1/auth/refresh-token Request body
        content:
          application/json:
            schema:
              type: object
      security:
        - APIKEY_1: []
      responses:
        "200":
          description: POST /v1/auth/refresh-token Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token
                required:
                  - status
                  - data
        "400":
          description: POST /v1/auth/refresh-token Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /v1/auth/microsoft/login:
    get:
      operationId: GetV1AuthMicrosoftLogin
      summary: Login with microsoft auth
      description: When user hits this endpoint, it would redirect user to sign in the url.
      responses:
        "200":
          description: GET /v1/auth/microsoft/login Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                required:
                  - status
                  - data
        "400":
          description: GET /v1/auth/microsoft/login Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /v1/auth/microsoft/login-url:
    get:
      operationId: GetV1AuthMicrosoftLoginUrl
      summary: Get microsoft login url
      description: Return microsoft login url
      responses:
        "200":
          description: GET /v1/auth/microsoft/login-url Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      url:
                        type: string
                      callbackUrl:
                        type: string
                    required:
                      - url
                      - callbackUrl
                required:
                  - status
                  - data
        "400":
          description: GET /v1/auth/microsoft/login-url Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
  /v1/auth/microsoft/callback:
    get:
      operationId: GetV1AuthMicrosoftCallback
      summary: Microsoft token callback
      description: Callback to get user token from Azure Issuer
      parameters:
        - name: code
          in: query
          required: true
          description: GET /v1/auth/microsoft/callback Parameter
          schema:
            type: string
      responses:
        "200":
          description: GET /v1/auth/microsoft/callback Positive response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: success
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                    required:
                      - token
                required:
                  - status
                  - data
        "400":
          description: GET /v1/auth/microsoft/callback Negative response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    const: error
                  error:
                    type: object
                    properties:
                      message:
                        type: string
                    required:
                      - message
                required:
                  - status
                  - error
              examples:
                example1:
                  value:
                    status: error
                    error:
                      message: Sample error message
components:
  schemas: {}
  responses: {}
  parameters: {}
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    APIKEY_1:
      type: apiKey
      in: header
      name: authorization
  links: {}
  callbacks: {}
tags: []
servers:
  - url: http://localhost:8090/api/
